# Generated by Django 5.1.7 on 2025-05-06 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecream',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icecream',
            name='title',
            field=models.CharField(default='2024-01-01', max_length=100),
            preserve_default=False,
        ),
    ]
